[versions]
spring-boot = "4.0.1"
spring-dependency-management = "1.1.7"
paho-client-mqttv3 = "1.2.5"
protobuf = "4.33.2"
jackson = "3.0.3"
postgresql = "42.7.8"
grpc = "1.76.0"
hibernate = "6.6.29.Final"
bouncy-castle = "1.83"

[libraries]
spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-oauth2-resource-server = { module = "org.springframework.boot:spring-boot-starter-oauth2-resource-server" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-integration-mqtt = { module = "org.springframework.integration:spring-integration-mqtt" }
spring-boot-starter-amqp = { module = "org.springframework.boot:spring-boot-starter-amqp" }
spring-boot-grpc = { module = "org.springframework.grpc:spring-grpc-spring-boot-starter" }
paho-client-mqttv3 = { module = "org.eclipse.paho:org.eclipse.paho.client.mqttv3", version.ref = "paho-client-mqttv3" }
protobuf = { module = "com.google.protobuf:protobuf-java", version.ref = "protobuf" }
jackson-core = { module = "tools.jackson.core:jackson-core", version.ref = "jackson" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
grpc-netty-shaded = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc" }
grpc-protobuf = { module = "io.grpc:grpc-protobuf", version.ref = "grpc" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc" }
hibernate-spatial = { module = "org.hibernate.orm:hibernate-spatial", version.ref = "hibernate" }
bouncy-castle-provider = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncy-castle" }
bouncy-castle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk18on", version.ref = "bouncy-castle" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
protobuf-plugin = { id = "com.google.protobuf", version = "0.9.6" }