spring:
  application:
    name: ingestion-service
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

queues:
  location:
    name: ${LOCATION_QUEUE_NAME}

mqtt:
  url: ${MQTT_URL}
  topic: ${MQTT_TOPIC}
  certificate: ${MQTT_CERTIFICATE_PATH}
  certificate-password: ${MQTT_CERTIFICATE_PASSWORD}