spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  grpc:
    client:
      channels:
        vehicle-service:
          address: vehicle-service:9090
          negotiation-type: plaintext

queues:
  location:
    name: ${LOCATION_QUEUE_NAME}